wheels = {
    "LEFT_MOTOR_FORWARD_VCC" : 20,
    "LEFT_MOTOR_FORWARD_GND" : 16,
    "LEFT_MOTOR_FORWARD_PWM" : 21,
    "LEFT_MORTOR_BACKWARD_VCC" : 23,
    "LEFT_MORTOR_BACKWARD_GND" : 24,
    "LEFT_MORTOR_BACKWARD_PWM" : 12,
    "RIGHT_MOTOR_FORWARD_VCC" : 19,
    "RIGHT_MOTOR_FORWARD_GND" : 26,
    "RIGHT_MOTOR_FORWARD_PWM" : 13,
    "RIGHT_MOTOR_BACKWARD_VCC" : 18,
    "RIGHT_MOTOR_BACKWARD_GND" : 27,
    "RIGHT_MOTOR_BACKWARD_PWM" : 17,
}