import RPi.GPIO as GPIO
import time

# Set GPIO Mode
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)

#Define the Pin, Pin_VCC/Pin_GND/Pin_PWM
LEFT_MOTOR_FORWARD_VCC = 20
LEFT_MOTOR_FORWARD_GND = 16
LEFT_MOTOR_FORWARD_PWM = 21

LEFT_MORTOR_BACKWARD_VCC = 23
LEFT_MORTOR_BACKWARD_GND = 24
LEFT_MORTOR_BACKWARD_PWM = 12

RIGHT_MOTOR_FORWARD_VCC = 19
RIGHT_MOTOR_FORWARD_GND = 26
RIGHT_MOTOR_FORWARD_PWM = 13

RIGHT_MOTOR_BACKWARD_VCC = 18
RIGHT_MOTOR_BACKWARD_GND = 27
RIGHT_MOTOR_BACKWARD_PWM = 17

#Define Pin as Output
GPIO.setup(LEFT_MOTOR_FORWARD_VCC,GPIO.OUT)
GPIO.setup(LEFT_MOTOR_FORWARD_GND,GPIO.OUT)
GPIO.setup(LEFT_MOTOR_FORWARD_PWM,GPIO.OUT)
GPIO.setup(LEFT_MORTOR_BACKWARD_VCC,GPIO.OUT)
GPIO.setup(LEFT_MORTOR_BACKWARD_GND,GPIO.OUT)
GPIO.setup(LEFT_MORTOR_BACKWARD_PWM,GPIO.OUT)
GPIO.setup(RIGHT_MOTOR_FORWARD_VCC,GPIO.OUT)
GPIO.setup(RIGHT_MOTOR_FORWARD_GND,GPIO.OUT)
GPIO.setup(RIGHT_MOTOR_FORWARD_PWM,GPIO.OUT)
GPIO.setup(RIGHT_MOTOR_BACKWARD_VCC,GPIO.OUT)
GPIO.setup(RIGHT_MOTOR_BACKWARD_GND,GPIO.OUT)
GPIO.setup(RIGHT_MOTOR_BACKWARD_PWM,GPIO.OUT)
GPIO.output(LEFT_MOTOR_FORWARD_VCC,GPIO.HIGH)
GPIO.output(LEFT_MOTOR_FORWARD_GND,GPIO.LOW)
GPIO.output(LEFT_MOTOR_FORWARD_PWM,GPIO.HIGH)
GPIO.output(LEFT_MORTOR_BACKWARD_VCC,GPIO.HIGH)
GPIO.output(LEFT_MORTOR_BACKWARD_GND,GPIO.LOW)
GPIO.output(LEFT_MORTOR_BACKWARD_PWM,GPIO.HIGH)
GPIO.output(RIGHT_MOTOR_FORWARD_VCC,GPIO.HIGH)
GPIO.output(RIGHT_MOTOR_FORWARD_GND,GPIO.LOW)
GPIO.output(RIGHT_MOTOR_FORWARD_PWM,GPIO.HIGH)
GPIO.output(RIGHT_MOTOR_BACKWARD_VCC,GPIO.HIGH)
GPIO.output(RIGHT_MOTOR_BACKWARD_GND,GPIO.LOW)
GPIO.output(RIGHT_MOTOR_BACKWARD_PWM,GPIO.HIGH)

#Initial PWM Object
pwm_LEFT_MOTOR_FORWARD_PWM = GPIO.PWM(LEFT_MOTOR_FORWARD_PWM,100)
pwm_LEFT_MORTOR_BACKWARD_PWM = GPIO.PWM(LEFT_MORTOR_BACKWARD_PWM,100)
pwm_RIGHT_MOTOR_FORWARD_PWM = GPIO.PWM(RIGHT_MOTOR_FORWARD_PWM,100)
pwm_RIGHT_MOTOR_BACKWARD_PWM = GPIO.PWM(RIGHT_MOTOR_BACKWARD_PWM,100)

#Action
#clockwise
def spin_clockwise(pin_pwm, speed):
    pin_pwm.start(speed)

#anticlockwise
def spin_anticlockwise(pin_vcc, pin_gnd, pin_pwm, speed):
    GPIO.output(pin_vcc,GPIO.LOW)
    GPIO.output(pin_gnd,GPIO.HIGH)
    pin_pwm.start(speed) 
#stop
def stop(pin_pwm, pin):
    pin_pwm.stop()
    GPIO.output(pin, GPIO.LOW)
    
try:
    # FORWARD - CLOCKWISE
    # spin_anticlockwise(LEFT_MOTOR_FORWARD_VCC, LEFT_MOTOR_FORWARD_GND, pwm_LEFT_MOTOR_FORWARD_PWM, 0)
    # pwm_LEFT_MOTOR_FORWARD_PWM.ChangeDutyCycle(10)
    # spin_anticlockwise(LEFT_MORTOR_BACKWARD_VCC, LEFT_MORTOR_BACKWARD_GND, pwm_LEFT_MORTOR_BACKWARD_PWM, 0)
    # pwm_LEFT_MORTOR_BACKWARD_PWM.ChangeDutyCycle(10)
    # spin_anticlockwise(RIGHT_MOTOR_FORWARD_VCC, RIGHT_MOTOR_FORWARD_GND, pwm_RIGHT_MOTOR_FORWARD_PWM, 0)
    # pwm_RIGHT_MOTOR_FORWARD_PWM.ChangeDutyCycle(10)
    # spin_anticlockwise(RIGHT_MOTOR_BACKWARD_VCC, RIGHT_MOTOR_BACKWARD_GND, pwm_RIGHT_MOTOR_BACKWARD_PWM, 0)
    # pwm_RIGHT_MOTOR_BACKWARD_PWM.ChangeDutyCycle(10)
    # time.sleep(5)
    
    # Backward - Anticlockwise
    # spin_clockwise(pwm_LEFT_MOTOR_FORWARD_PWM, 0)
    # pwm_LEFT_MOTOR_FORWARD_PWM.ChangeDutyCycle(10)
    # spin_clockwise(pwm_LEFT_MORTOR_BACKWARD_PWM, 0)
    # pwm_LEFT_MORTOR_BACKWARD_PWM.ChangeDutyCycle(10)
    # spin_clockwise(pwm_RIGHT_MOTOR_FORWARD_PWM, 0)
    # pwm_RIGHT_MOTOR_FORWARD_PWM.ChangeDutyCycle(10)
    # spin_clockwise(pwm_RIGHT_MOTOR_BACKWARD_PWM, 0)
    # pwm_RIGHT_MOTOR_BACKWARD_PWM.ChangeDutyCycle(10)
    # time.sleep(10)

    # #turn_left
    # spin_clockwise(pwm_LEFT_MOTOR_FORWARD_PWM, 0)
    # pwm_LEFT_MOTOR_FORWARD_PWM.ChangeDutyCycle(10)
    # spin_clockwise(pwm_LEFT_MORTOR_BACKWARD_PWM, 0)
    # pwm_LEFT_MORTOR_BACKWARD_PWM.ChangeDutyCycle(10)
    # spin_anticlockwise(RIGHT_MOTOR_FORWARD_VCC, RIGHT_MOTOR_FORWARD_GND, pwm_RIGHT_MOTOR_FORWARD_PWM, 0)
    # pwm_RIGHT_MOTOR_FORWARD_PWM.ChangeDutyCycle(10)
    # spin_anticlockwise(RIGHT_MOTOR_BACKWARD_VCC, RIGHT_MOTOR_BACKWARD_GND, pwm_RIGHT_MOTOR_BACKWARD_PWM, 0)
    # pwm_RIGHT_MOTOR_BACKWARD_PWM.ChangeDutyCycle(10)
    # time.sleep(10)

    #turn_right
    # spin_anticlockwise(LEFT_MOTOR_FORWARD_VCC, LEFT_MOTOR_FORWARD_GND, pwm_LEFT_MOTOR_FORWARD_PWM, 0)
    # pwm_LEFT_MOTOR_FORWARD_PWM.ChangeDutyCycle(10)
    # spin_anticlockwise(LEFT_MORTOR_BACKWARD_VCC, LEFT_MORTOR_BACKWARD_GND, pwm_LEFT_MORTOR_BACKWARD_PWM, 0)
    # pwm_LEFT_MORTOR_BACKWARD_PWM.ChangeDutyCycle(10)
    # spin_clockwise(pwm_RIGHT_MOTOR_FORWARD_PWM, 0)
    # pwm_RIGHT_MOTOR_FORWARD_PWM.ChangeDutyCycle(10)
    # spin_clockwise(pwm_RIGHT_MOTOR_BACKWARD_PWM, 0)
    # pwm_RIGHT_MOTOR_BACKWARD_PWM.ChangeDutyCycle(10)
    
    #turn_left staticlldy
    spin_clockwise(pwm_LEFT_MOTOR_FORWARD_PWM, 0)
    pwm_LEFT_MOTOR_FORWARD_PWM.ChangeDutyCycle(5)
    spin_clockwise(pwm_LEFT_MORTOR_BACKWARD_PWM, 0)
    pwm_LEFT_MORTOR_BACKWARD_PWM.ChangeDutyCycle(5)
    spin_anticlockwise(RIGHT_MOTOR_FORWARD_VCC, RIGHT_MOTOR_FORWARD_GND, pwm_RIGHT_MOTOR_FORWARD_PWM, 0)
    pwm_RIGHT_MOTOR_FORWARD_PWM.ChangeDutyCycle(5)
    spin_anticlockwise(RIGHT_MOTOR_BACKWARD_VCC, RIGHT_MOTOR_BACKWARD_GND, pwm_RIGHT_MOTOR_BACKWARD_PWM, 0)
    pwm_RIGHT_MOTOR_BACKWARD_PWM.ChangeDutyCycle(5)
    time.sleep(10)
    
except KeyboardInterrupt:
    pass

finally:
    stop(pwm_LEFT_MOTOR_FORWARD_PWM, LEFT_MOTOR_FORWARD_PWM)
    stop(pwm_LEFT_MORTOR_BACKWARD_PWM, LEFT_MORTOR_BACKWARD_PWM)
    stop(pwm_RIGHT_MOTOR_FORWARD_PWM ,RIGHT_MOTOR_FORWARD_PWM)
    stop(pwm_RIGHT_MOTOR_BACKWARD_PWM, RIGHT_MOTOR_BACKWARD_PWM)
    GPIO.cleanup()


    